version: "3"
services:
  api-gateway:
    build: "./api-gateway"
    depends_on:
      - listing
      - users
    ports:
      - 7070:7070
    environment:
      - PORT=7070
    volumes:
      - ./api-gateway:/opt/app
  listing:
    build: "./listing"
    environment:
      - DB_URI=mongodb://mongodb/listing
      - PORT=8082
      - AWS_ACCESS_KEY=AKIA6ADRTZKSS6A43E2O
      - AWS_SECRET_KEY=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
    volumes:
      - ./listing:/opt/app
    ports:
      - 8082:8082
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  users:
    build: "./users"
    depends_on:
      - usersdb
    environment:
      - PORT=8081
      - DB_URI=mongodb://usersdb/user
      - SALT=testing
    ports:
      - 8081:8081
    volumes:
      - ./users:/opt/app

  usersdb:
    image: mongo:latest
    ports:
      - 27018:27018
    volumes:
      - ./data:/data/users

volumes:
  data:
